### ISSUE TITLE
network_and_bandwidth_check validates # of NICs not # of IP addresses

### ISSUE THREAD

**Issue by jlwalke2** [sassoftware/virk#21]
I believe the issue with Consul is that it must be explicitly told which private IP address to bind to during startup if there are more than one.  

In an environment with multiple networking devices but only a single IP address the network_and_bandwidth_check fails, though Consul startup is unaffected.

**Comment by erwangranger** [comment]
That is a good point. 
Because the remedy is to set something like `consul_bind_adapter=eth0` in the inventory, I have been thinking more of network interfaces being up. (you can also use the IP instead of the NIC name, but that'd likely be more troublesome). 

So, I think that replacing the code with: 
```
ip -4 -o addr | awk '!/^[0-9]*: ?lo|link\/ether/ {gsub("/", " "); print $4}'
```
should yield decent results. 
In my testing it returns one line per IPv4, and excludes the loopback interface. 
Sounds reasonable?

**Comment by jlwalke2** [comment]
That change does appear to resolve the issue in my environment.  Thx!

**Comment by thpang** [comment]
Code has been merged. Closing this issue.
