### ISSUE TITLE
3.3 clone link, missing .yml files?

### ISSUE THREAD

**Issue by oagn** [sassoftware/virk#54]
We copied the clone address to download the 3.3 branch, but did not  get any of the .yml files. 
Has anyone else experienced this issue?

Solution: Download the zip file

**Comment by thpang** [comment]
@oagn thanks asking the question. I believe you may be looking at the master branch instead of the viya-3.3 branch. If you have cloned the repo you can change your checkout location with the following command form your repo directory:

`$ git checkout viya-3.3`

That should get you what you need. 

Of course downloading the zip file for viya-3.3 would accomplish the same thing.
