### ISSUE TITLE
remove the vi_ and the va_ pre-install playbooks ?

### ISSUE THREAD

**Issue by erwangranger** [sassoftware/virk#95]
I would suggest removing the following 2 files in https://github.com/sassoftware/virk/tree/viya-3.4/playbooks/pre-install-playbook:
* va_pre_install_playbook.yml
* vi_pre_install_playbook.yml

Given that we strive to have something that is easy to use, it would be better to only have viya_pre_install_playbook.yml alone, and strive to have it fulfill all Viya deployment requirements. 

The current existence of a vi_ file makes it sound like it also covers Visual Investigator, which it does not at the moment.

**Comment by hahewlet** [comment]
Erwan makes a good point. I assumed that file had something to do with Visual Investigator.

**Comment by niklasnil** [comment]
After discussing with Erwan about his suggestion to only keep the viya_pre_install_playbook.yml playbook, then I think it would also be very informative to state in the README file that this playbook exclude any pre-install settings for Visual Investigator (VI) or Event Stream Prosessing (ESP) for the moment, since these solutions are also Viya products.
Both VA/VS/VDMML and Visual Investigator now use same Deployment Guide in SAS Viya 3.4, so it could easily be mistaken that even this playbook will also make VI specific settings.

**Comment by kevinlinglesas** [comment]
This issue has been addressed in [Initial Release](https://github.com/sassoftware/viya-ark/releases/tag/v0.1) of [Viya ARK](https://github.com/sassoftware/viya-ark) project.  See DEPENB-1373 release note.
